name: Add comment on push

on:
  push:
    branches: [orange-hrm-branch]

permissions:
  pull-requests: write

jobs:
  add-comment:
    name: Post welcome comment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add comment to pull request
        run: |
          gh pr list --json number --state open --base orange-hrm-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


