name: Add comment on push

on:
  push:
    branches: [orange-hrm-branch]
permissions:
  pull-requests: write

jobs:
  add-comment:
    name: Post welcome comment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add comment to pull request
        run: |
          PR_NUMBER=$(gh pr list --json number --state open --base main | jq -r '.[0].number')
          COMMENT_BODY="Welcome to the repository!"
          gh pr comment $PR_NUMBER --body "$COMMENT_BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


